# Generated by Django 6.0.3 on 2026-03-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('per_unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_hand', models.IntegerField(default=0)),
                ('free_to_use', models.IntegerField(default=0)),
            ],
        ),
    ]
