# Generated by Django 6.0.3 on 2026-03-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocationApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='district',
        ),
    ]
