# Generated by Django 6.0.3 on 2026-03-14 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WarehouseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('schedule_date', models.DateField()),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('in-progress', 'In Progress')], default='ready', max_length=20)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='WarehouseApp.warehouse')),
            ],
        ),
    ]
