# Generated by Django 6.0.3 on 2026-03-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LocationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('w_name', models.CharField(max_length=255)),
                ('w_location', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationApp.location')),
            ],
        ),
    ]
